package com.kitchen.dto;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class CocktailDtoBuilder {
    public static final String DRINK_NAME_TEST = "Malibu";
    public static CocktailListDto buildExampleCocktail() {
        CocktailListDto cocktailListDto = new CocktailListDto();
        CocktailDto cocktailDto = new CocktailDto.CocktailDtoBuilder()
                .dateModified("2020-10-12")
                .idDrink("10")
                .strAlcoholic("true")
                .strCategory("Milk")
                .strCreativeCommonsConfirmed("")
                .strDrink("Malibu")
                .strDrinkAlternate("lol")
                .strDrinkDE("")
                .strDrinkES("")
                .strDrinkFR("")
                .strDrinkThumb("")
                .strDrinkZHHANS("")
                .strDrinkZHHANT("")
                .strGlass("")
                .strIBA("")
                .strIngredient1("rum")
                .strIngredient2("coconut milk")
                .strIngredient3("pineapple juice")
                .strIngredient4("ice")
                .strIngredient5("sugar liqueur")
                .strIngredient6("")
                .strIngredient7("")
                .strIngredient8("")
                .strIngredient9("")
                .strIngredient10("")
                .strIngredient11("")
                .strIngredient12("")
                .strIngredient13("")
                .strIngredient14("")
                .strIngredient15("")
                .strInstructions("")
                .strInstructionsDE("")
                .strInstructionsES("")
                .strInstructionsFR("")
                .strInstructionsZHHANS("")
                .strInstructionsZHHANT("")
                .strMeasure1("50ml")
                .strMeasure2("50ml")
                .strMeasure3("100ml")
                .strMeasure4("some")
                .strMeasure5("10ml")
                .strMeasure6("")
                .strMeasure7("")
                .strMeasure8("")
                .strMeasure9("")
                .strMeasure10("")
                .strMeasure11("")
                .strMeasure12("")
                .strMeasure13("")
                .strMeasure14("")
                .strMeasure15("")
                .strTags("drink drank drunk")
                .strVideo("www.youtube.com/123PinaColadePijeszTy")
                .build();
        cocktailListDto.setCocktails(Arrays.asList(cocktailDto));
        return cocktailListDto;
    }

    public static CocktailListDto buildEmptyList() {
        List<CocktailDto> emptyList = new ArrayList<>();
        CocktailListDto cocktailListDto = new CocktailListDto();
        cocktailListDto.setCocktails(emptyList);
        return cocktailListDto;
    }

    public static CocktailListDto buildExampleCocktails() {
        CocktailListDto cocktailListDto = new CocktailListDto();
        List<CocktailDto> cocktails = new ArrayList<>();
        CocktailDto cocktailDto = new CocktailDto.CocktailDtoBuilder()
                .dateModified("2020-10-12")
                .idDrink("10")
                .strAlcoholic("true")
                .strCategory("Milk")
                .strCreativeCommonsConfirmed("")
                .strDrink("Malibu")
                .strDrinkAlternate("lol")
                .strDrinkDE("")
                .strDrinkES("")
                .strDrinkFR("")
                .strDrinkThumb("")
                .strDrinkZHHANS("")
                .strDrinkZHHANT("")
                .strGlass("")
                .strIBA("")
                .strIngredient1("rum")
                .strIngredient2("coconut milk")
                .strIngredient3("pineapple juice")
                .strIngredient4("ice")
                .strIngredient5("sugar liqueur")
                .strIngredient6("")
                .strIngredient7("")
                .strIngredient8("")
                .strIngredient9("")
                .strIngredient10("")
                .strIngredient11("")
                .strIngredient12("")
                .strIngredient13("")
                .strIngredient14("")
                .strIngredient15("")
                .strInstructions("")
                .strInstructionsDE("")
                .strInstructionsES("")
                .strInstructionsFR("")
                .strInstructionsZHHANS("")
                .strInstructionsZHHANT("")
                .strMeasure1("50ml")
                .strMeasure2("50ml")
                .strMeasure3("100ml")
                .strMeasure4("some")
                .strMeasure5("10ml")
                .strMeasure6("")
                .strMeasure7("")
                .strMeasure8("")
                .strMeasure9("")
                .strMeasure10("")
                .strMeasure11("")
                .strMeasure12("")
                .strMeasure13("")
                .strMeasure14("")
                .strMeasure15("")
                .strTags("drink drank drunk")
                .strVideo("www.youtube.com/123PinaColadePijeszTy")
                .build();

        CocktailDto cocktailDtoSecond = new CocktailDto.CocktailDtoBuilder()
                .dateModified("2020-10-12")
                .idDrink("10")
                .strAlcoholic("true")
                .strCategory("Milk")
                .strCreativeCommonsConfirmed("")
                .strDrink("Malibu")
                .strDrinkAlternate("lol")
                .strDrinkDE("")
                .strDrinkES("")
                .strDrinkFR("")
                .strDrinkThumb("")
                .strDrinkZHHANS("")
                .strDrinkZHHANT("")
                .strGlass("")
                .strIBA("")
                .strIngredient1("rum")
                .strIngredient2("coconut milk")
                .strIngredient3("pineapple juice")
                .strIngredient4("ice")
                .strIngredient5("sugar liqueur")
                .strIngredient6("")
                .strIngredient7("")
                .strIngredient8("")
                .strIngredient9("")
                .strIngredient10("")
                .strIngredient11("")
                .strIngredient12("")
                .strIngredient13("")
                .strIngredient14("")
                .strIngredient15("")
                .strInstructions("")
                .strInstructionsDE("")
                .strInstructionsES("")
                .strInstructionsFR("")
                .strInstructionsZHHANS("")
                .strInstructionsZHHANT("")
                .strMeasure1("50ml")
                .strMeasure2("50ml")
                .strMeasure3("100ml")
                .strMeasure4("some")
                .strMeasure5("10ml")
                .strMeasure6("")
                .strMeasure7("")
                .strMeasure8("")
                .strMeasure9("")
                .strMeasure10("")
                .strMeasure11("")
                .strMeasure12("")
                .strMeasure13("")
                .strMeasure14("")
                .strMeasure15("")
                .strTags("drink drank drunk")
                .strVideo("www.youtube.com/123PinaColadePijeszTy")
                .build();
        cocktails.add(cocktailDto);
        cocktails.add(cocktailDtoSecond);
        cocktailListDto.setCocktails(cocktails);
        return cocktailListDto;

    }
}
