package com.kitchen.dto;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class MealDtoBuilder {
    public static final String MEAL_NAME_TEST = "Chicken";

    public static MealListDto buildExampleMeal() {
        MealListDto mealListDto = new MealListDto();
        MealDto mealDto = new MealDto.MealDtoBuilder()
                .idMeal("1")
                .strMeal("Chicken")
                .strMealThumb("")
                .dateModified("2020-11-10")
                .strArea("Asia")
                .strCategory("Meat")
                .strDrinkAlternate("")
                .strIngredient1("Chicken")
                .strIngredient2("Salt")
                .strIngredient3("Water")
                .strIngredient4("Garlic")
                .strIngredient5("Pepper")
                .strIngredient6("Paprika")
                .strIngredient7("Eggs")
                .strIngredient8("Milk")
                .strIngredient9("Flour")
                .strIngredient10("Ice")
                .strIngredient11("Oil")
                .strIngredient12("")
                .strIngredient13("")
                .strIngredient14("")
                .strIngredient15("")
                .strIngredient16("")
                .strIngredient17("")
                .strIngredient18("")
                .strIngredient19("")
                .strIngredient20("")
                .strInstructions("Food Imperor mówi 'wpiernicz to wszystko do gaaarnka i nie badz leniwy!")
                .strMeasure1("")
                .strMeasure2("")
                .strMeasure3("")
                .strMeasure4("")
                .strMeasure5("")
                .strMeasure6("")
                .strMeasure7("")
                .strMeasure8("")
                .strMeasure9("")
                .strMeasure10("")
                .strMeasure11("")
                .strMeasure12("")
                .strMeasure13("")
                .strMeasure14("")
                .strMeasure15("")
                .strMeasure16("")
                .strMeasure17("")
                .strMeasure18("")
                .strMeasure19("")
                .strMeasure20("")
                .strSource("")
                .strTags("")
                .strYoutube("")
                .build();
        mealListDto.setMeals(Arrays.asList(mealDto));
        return mealListDto;
    }

    public static MealListDto buildExampleMeals() {
        List<MealDto> meals =new ArrayList<>();
        MealListDto mealListDto = new MealListDto();
        MealDto mealDto = new MealDto.MealDtoBuilder()
                .idMeal("1")
                .strMeal("Chicken")
                .strMealThumb("")
                .dateModified("2020-11-10")
                .strArea("Asia")
                .strCategory("Meat")
                .strDrinkAlternate("")
                .strIngredient1("Chicken")
                .strIngredient2("Salt")
                .strIngredient3("Water")
                .strIngredient4("Garlic")
                .strIngredient5("Pepper")
                .strIngredient6("Paprika")
                .strIngredient7("Eggs")
                .strIngredient8("Milk")
                .strIngredient9("Flour")
                .strIngredient10("Ice")
                .strIngredient11("Oil")
                .strIngredient12("")
                .strIngredient13("")
                .strIngredient14("")
                .strIngredient15("")
                .strIngredient16("")
                .strIngredient17("")
                .strIngredient18("")
                .strIngredient19("")
                .strIngredient20("")
                .strInstructions("Food Imperor mówi 'wpiernicz to wszystko do gaaarnka i nie badz leniwy!")
                .strMeasure1("")
                .strMeasure2("")
                .strMeasure3("")
                .strMeasure4("")
                .strMeasure5("")
                .strMeasure6("")
                .strMeasure7("")
                .strMeasure8("")
                .strMeasure9("")
                .strMeasure10("")
                .strMeasure11("")
                .strMeasure12("")
                .strMeasure13("")
                .strMeasure14("")
                .strMeasure15("")
                .strMeasure16("")
                .strMeasure17("")
                .strMeasure18("")
                .strMeasure19("")
                .strMeasure20("")
                .strSource("")
                .strTags("")
                .strYoutube("")
                .build();

        MealDto mealDtoSecond = new MealDto.MealDtoBuilder()
                .idMeal("1")
                .strMeal("Chicken")
                .strMealThumb("")
                .dateModified("2020-11-10")
                .strArea("Asia")
                .strCategory("Meat")
                .strDrinkAlternate("")
                .strIngredient1("Chicken")
                .strIngredient2("Salt")
                .strIngredient3("Water")
                .strIngredient4("Garlic")
                .strIngredient5("Pepper")
                .strIngredient6("Paprika")
                .strIngredient7("Eggs")
                .strIngredient8("Milk")
                .strIngredient9("Flour")
                .strIngredient10("Ice")
                .strIngredient11("Oil")
                .strIngredient12("")
                .strIngredient13("")
                .strIngredient14("")
                .strIngredient15("")
                .strIngredient16("")
                .strIngredient17("")
                .strIngredient18("")
                .strIngredient19("")
                .strIngredient20("")
                .strInstructions("Food Imperor mówi 'wpiernicz to wszystko do gaaarnka i nie badz leniwy!")
                .strMeasure1("")
                .strMeasure2("")
                .strMeasure3("")
                .strMeasure4("")
                .strMeasure5("")
                .strMeasure6("")
                .strMeasure7("")
                .strMeasure8("")
                .strMeasure9("")
                .strMeasure10("")
                .strMeasure11("")
                .strMeasure12("")
                .strMeasure13("")
                .strMeasure14("")
                .strMeasure15("")
                .strMeasure16("")
                .strMeasure17("")
                .strMeasure18("")
                .strMeasure19("")
                .strMeasure20("")
                .strSource("")
                .strTags("")
                .strYoutube("")
                .build();


        meals.add(mealDto);
        meals.add(mealDtoSecond);
        mealListDto.setMeals(meals);
        return mealListDto;
    }
    public static MealListDto buildEmptyList() {
        List<MealDto> emptyList = new ArrayList<>();
        MealListDto mealListDto = new MealListDto();
        mealListDto.setMeals(emptyList);
        return mealListDto;
    }
}
